title: Erica Waters CV
profile_img: /assets/img/headshot.jpg
icon_img: /assets/img/icon.webp

name: "Erica Waters"
job: "Research Scientist | Roboticist | Rehabilitation Engineer"

#phone_number: 012-345-6789
address: Philadelphia, PA
email: waterica@engineering.upenn.edu
linkedin_username: erica-waters-747b15192/
# github_username: waterica
scholar_userid: 2C-naI8AAAAJ
orcid_id: 0000-0003-1495-8423
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag