subject: Service
listing-order: 6
icon: "/assets/img/globe.svg"
contents:
  - title: Mentorship & Outreach
    description: 
      - "**Rehabilitation Robotics Lab (2021-Present)**: Supervised research projects for 15+ students, ranging from high school to graduate school, with a focus on research pipeline programs. Mentees have presented at program closing ceremonies, Penn Medicine PM&R Research Week, and Penn Global Health Day."
      - "**Free Library of Philadelphia (2026)**: Designed and led a two-part afterschool robotics outreach workshop for ~40 K-12 students at the Roxborough Library Branch. ([Read More](https://www.timesherald.com/2026/04/27/friends-group-helps-power-roxborough-library/))" 
      - "**Franklin Institute (2025)**: Designed and led an afterschool robotics and biosensing outreach workshop for ~15 high school students at a science museum in Philadelphia. ([Read More](https://www.linkedin.com/posts/stemeducation-rehabilitationrobotics-humanrobotinteraction-share-7326606928682393600-wJLa/?utm_source=share&utm_medium=member_desktop&rcm=ACoAAC1fGucB46r5odaPBMC1dAZLwNWPcsYNqhk))"
      - "**Penn GEMS Engineering Camp (2022-2023)**: Designed and led an engineering design workshop for middle school students as part of a summer STEM outreach camp. ([Read More](https://pennandphilly.upenn.edu/stories/philly-middle-schoolers-enjoy-a-summer-of-exploring-engineering/))" 
  - title: Institutional Service
    description:
      - "**Panelist**: GRASP External Review PhD Panel (2024), GRASP on Robotics Seminar (2023, 2024), Penn Graduate Women In Science and Engineering Research Panel (2025)" 
      - "**Poster Judge**: Penn Engineering Research Experiences for Undergraduates Symposium (2024)" 
      - "**Tour Guide**: GRASP Lab Tours (2021-2026), Penn Medicine PM&R Research Week Lab Tour (2024), IEEE International Conference on Robotics & Automation Rehabilitation Robotics Lab Tour (2023)"
  - title: Peer Reviewer
    description: 
      - "**Journal**: IEEE Robotics and Automation Letters (2026)"
      - "**Conference**: International IEEE/EMBS Conference on Neural Engineering (2025), International Conference On Rehabilitation Robotics (2025), International Conference for Biomedical Robotics and Biomechatronics (2024)"
  - title: Professional Society Memberships
    description: 
      - "**International Consortium for Rehabilitation Robotics (ICORR)**, Graduate Student Member, 2024-Present" 
      - "**IEEE Robotics and Automation Society**, Graduate Student Member, 2024-Present"
      - "**IEEE Engineering in Medicine and Biology Society**, Graduate Student Member, 2024-Present"